//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gia
    {
        public System.DateTime NgayAdGia { get; set; }
        public string MaThucDon { get; set; }
        public double Gia1 { get; set; }
    
        public virtual ThucDon ThucDon { get; set; }
    }
}
