//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phancong
    {
        public int ID { get; set; }
        public System.DateTime NgayPC { get; set; }
        public int Ca { get; set; }
        public string MaNV { get; set; }
        public string MaBanAn { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
